config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get  'pages/index'
  get  'pages/users'
  get  'chatrooms/index'


   


  # get 'chatrooms/index', :to => "chatrooms/index", :as => chatroom_index


  # changes login to /login
	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end	

	

	devise_scope :user do
		get 'sign_up', to: 'devise/registrations#new'
	end	


	resources :chatrooms do
		resource :chatroom_users
	    resources :messages
	end


	resources :posts do 
		member do
			put 'like' => 'posts#vote'
		end
		resources :comments
	end 

	resources :tags

	



	

	# namespace :admin do
 #  		resources :chatromms, :pages
	# end

  resources :direct_messages

  root to: "pages#index"
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy


  validates :name, presence: true;
  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }

  def self.direct_message_for_users(users)
    # user_ids = users.map(&:id).sort
    user_ids = users.map(&:username).sort
    name = "Direct Message - #{user_ids.join(" - ")}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      # create a new chatroom
      chatroom = new(name: name, direct_message: true)
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.public_channels
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.userid = current_user.id

    respond_to do |format|

      if @chatroom.save
        @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
          
  <!-- <div class="input-group mb-3"> -->
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :chatroom_name, class:"form-control", placeholder: 'Name of Chatrooom' %>
    </div>
<!--   </div> -->






  <div class="actions">
      <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<div class="post-form-wrapper">
	<div class="post-form">
		<h3 class="login-text" >Update <%= @chatroom.name  %> channel</h3>
		<%= render 'form', chatroom: @chatroom %>
		<br>
		<%= link_to 'Show', @chatroom, id: "edit", class: 'btn btn-success' %> 
		<%= link_to 'Back', chatrooms_path, class: 'btn btn-danger' %>
	</div>
</div>

app/views/chatrooms/index.html.erb
<div id="channel-wrapper">

  <div id="chatroom-logo">
      <%= image_tag("logo/Logo-good-small.png") %>
  </div>
  
  <div class="back-btn">
    <%= link_to 'Back', root_path, class: 'btn back-btn btn-danger' %>
  </div>



  <div class="channel-box">
    <h2 id="channel-heading">Channels</h2>

      <div class="chat-image">
         <%= image_tag("chat-sm.png", id: "channel-logo" ) %>
      </div>
      <div class="line"></div>
      <% @chatrooms.each do |chatroom| %>
        <div class="channel-name">
          <!-- <p id="channel-name"><%= chatroom.name %></p> -->

          <%= link_to chatroom.name, chatroom_chatroom_users_path(chatroom), class: "", id: "channel-name", method: :post %>


          <% if current_user.id == chatroom.userid %>
            <%= link_to 'UPDATE', edit_chatroom_path(chatroom), class: "btn btn-primary buttons", id: "update" %>

            <%= link_to 'REMOVE', chatroom, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger buttons", id: "remove" %>

             <%= link_to "LEAVE", chatroom_chatroom_users_path(chatroom), class: "btn btn-success buttons", id: "leave", method: :delete %>

           <!--  <%= link_to "JOIN", chatroom_chatroom_users_path(chatroom), class: "btn btn-success buttons", id: "join", method: :post %> -->
          <% else %>
            <%= link_to "LEAVE", chatroom_chatroom_users_path(chatroom), class: "btn btn-success buttons", id: "leave", method: :delete %>

           <!--  <%= link_to "JOIN", chatroom_chatroom_users_path(chatroom), class: "btn btn-success buttons", id: "join", method: :post %> -->
          <% end %>
        </div>
        <div class="line"></div>
      <% end %>

      <div class="add-channel">
        <%= link_to 'Add Channel + ', new_chatroom_path, id: "add-btn", class: 'btn btn-primary' %>
      </div>


  </div>

</div>

app/views/chatrooms/new.html.erb
<div class="post-form-wrapper">
	<div class="post-form">
	    <h3 class="login-text" >Create a new channel</h3>
		<%= render 'form', chatroom: @chatroom %>
		<br>
		<%= link_to 'Back', chatrooms_path, class: 'btn btn-danger' %>
	</div>
</div>

app/views/chatrooms/show.html.erb
<div class="page-wrapper">
	
<div class="sidebar-right">


  <div class="sidebar-wrappper">

  
 <div id="back-btn">
    <%= link_to 'Back', chatrooms_path, class: "btn btn-danger", id: "back-btn" %>
  </div>
  <% if current_user.id == @chatroom.userid %>
  <div id="edit-btn">
    <%= link_to 'Edit', edit_chatroom_path(@chatroom), class: "btn btn-success", id: "edit-btn" %> 
  </div>
  <div id="remove-btn">
    <%= link_to 'Remove', @chatroom, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", id: "remove-btn" %>
  </div>
  <% end %>

  <%= image_tag("logo/Logo-good-small.png", id: "chat-logo", class: "img-fluid") %>


  <p id="heading"><%= current_user.username %>'s Current Chatrooms</p>

  <% if user_signed_in? %>
	<div id="chatroom-names">
		<% current_user.chatrooms.public_channels.each do |chatroom| %>
	        <%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id}, class: "chatroom-names-wrapper" %>
	     <% end %>
	</div>
  <% end %>

<!--   <p id="notice"><%= notice %></p> -->


   

     

  </div>



</div>


<div class="sidebar-left">
  <div id="user-sidebar-wrapper">
    <div class="user-icon">
        <i class="fas fa-user"></i>
    </div>

    <!-- <img class="faces" width="40" src="elon.jpg">
    <p class="face-name">Elon Musk</p> -->
	<div class="users">
     <% (User.all -  [current_user]).each do |user| %>
	    <%= link_to image_tag(user.profile_picture.url, class: "faces", width: '40', style: 'border-radius: 100px;'), direct_message_path(user.id), :method => :get, data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %>
	    <p><%= user.username  %></p>
	 <% end %>
	</div>

    
  </div>
</div>




  <div class="main">
    <div class="chat-area-wrapper">
    	<strong><%= @chatroom.name  %></strong>
		<hr>
		<% unread_messages = false %>
		<div data-behavior='messages' data-chatroom-id='<%= @chatroom.id  %>'>


    	<% @messages.each do |message| %>
    		<% if !unread_messages && @chatroom_user.last_read_at < message.created_at %>
    			<% unread_messages = true %>
    			<div class="strike"><span>Unread Messages</span></div>
			 <% end %>
			 <%= render message  %>
		 <% end %>
     				 
  		</div>
		
		<%= form_for [@chatroom, Message.new], remote: true do |f| %>
  			<div class="form-group shadow-textarea">
      		<%= f.text_area :body, rows: 3, class: "form-control z-depth-1", autofocus: true, id: "text-box"  %>
      		<br>
  		<%= f.submit "Send", class: "btn btn-primary send-btn"  %>
  		<% end  %>
    	</div>

	</div>



</div>