config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get  'pages/index'
  get  'pages/users'
  get  'chatrooms/index'


   


  # get 'chatrooms/index', :to => "chatrooms/index", :as => chatroom_index


  # changes login to /login
	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end	

	

	devise_scope :user do
		get 'sign_up', to: 'devise/registrations#new'
	end	


	resources :chatrooms do
		resource :chatroom_users
	    resources :messages
	end


	resources :posts do 
		member do
			put 'like' => 'posts#vote'
		end
		resources :comments
	end 

	resources :tags

	



	

	# namespace :admin do
 #  		resources :chatromms, :pages
	# end

  resources :direct_messages

  root to: "pages#index"
end

app/views/pages/index.html.erb
<div id="fakeLoader"></div>
<div id="wrapper">
  
  <div id="top-content">
    

        <section id="welcome">

          <%= image_tag (current_user.profile_picture.url(:thumb)), id: "profile" %>
          <div id="name">
            <p id=""><%= current_user.first_name.upcase_first%> <%= current_user.last_name.upcase_first  %></p>
            <p id=""><%= current_user.course.upcase_first  %> - Level <%= current_user.degree_level  %></p>
          </div>


          <%= image_tag("logo/Logo-good.png", id: "logo-heading", width: 350, class: "animated pulse" ) %>

         

          <h2 class="animated fadeInUp" id="welcome-heading">Welcome to myuel <%= current_user.username.upcase_first %>!</h2>
          <h3 class="animated fadeInUp" id="welcome-sub-heading">Your number one place for social life at university </h3>

        </section>

  </div> <!-- end of top-content -->

  <div id="main-content">
      <section id="boxes">
        
            <div id="box1">
              <!-- <img class="box-image"src="profile.png"> -->
              <div class="box-headings">
                <h3 id="profile-text-heading">Manage Profile</h3>
                <p class="box-sub-heading">Update your account here</p>
              </div>

              <div class="box-images">
                <%= image_tag("boxes/profile-1.png", class: "box-image-1") %>
                <%= image_tag("boxes/profile-2.png", class: "box-image-2") %>
                <%= image_tag("boxes/profile-3.png", class: "box-image-3") %>
              </div>


              <div class="box-bottom">
                <%= link_to edit_user_registration_path do %>
                  <button id="profile-btn" class="btn btn-primary">View Profile</button>
                 <% end %>
              </div>
             
          </div>
        
        

         
        <div id="box2">
              <!-- <img class="box-image"src="profile.png"> -->
              <div class="box-headings">
                <h3 id="events-text-heading">Create events</h3>
                <p class="box-sub-heading">Create events for all your classmates to see! </p>
              </div>

              <div class="box-images">
                <%= image_tag("boxes/event-1.png", class: "box-image-1") %>
                <%= image_tag("boxes/event-2.png", class: "box-image-2") %>
                <%= image_tag("boxes/event-3.png", class: "box-image-3") %>
              </div>


              <div class="box-bottom">
                <%= link_to posts_path,  method: :get do %>
                  <button id="event-btn" class="btn btn-primary">Create events</button>
                <% end %>
              </div>
          </div>
        
        

         
        <div id="box3">
              <!-- <img class="box-image"src="profile.png"> -->
              <div class="box-headings">
                <h3 id="chat-text-heading">Live chat with friends</h3>
                <p class="box-sub-heading">Create channels and direct message friends</p>
              </div>

              <div class="box-images">
                <%= image_tag("boxes/chat-1.png", class: "box-image-1") %>
                <%= image_tag("boxes/chat-2.png", class: "box-image-2") %>
                <%= image_tag("boxes/chat-3.png", class: "box-image-3") %>
              </div>


              <div class="box-bottom">
                <%= link_to chatrooms_path do %>
                  <button id="chat-btn" class="btn btn-primary">Live chat</button>
                <% end %>
              </div>
          </div>


          <div id="box4">
              <!-- <img class="box-image"src="profile.png"> -->
              <div class="box-headings">
                <h3 id="user-text-heading">View all users</h3>
                <p class="box-sub-heading">View your friends public information</p>
              </div>

              <div class="box-images">
                <%= image_tag("boxes/user-1.png", class: "box-image-1") %>
                <%= image_tag("boxes/user-2.png", class: "box-image-2") %>
                <%= image_tag("boxes/user-3.png", class: "box-image-3") %>
              </div>


              <div class="box-bottom">
                <%= link_to pages_users_path do %>
                  <button id="user-btn" class="btn btn-primary">View all users</button>
                <% end %>
              </div>
          </div>
       



        

      

      </section>
  </div>







</div> <!-- wrapper -->
<script type="text/javascript">

$("#fakeLoader").fakeLoader({
  timeToHide:1200, //Time in milliseconds for fakeLoader disappear

  zIndex:"999",//Default zIndex

  spinner:"spinner1",//Options: 'spinner1', 'spinner2', 'spinner3', 'spinner4', 'spinner5', 'spinner6', 'spinner7'

  bgColor:"#216c98", //Hex, RGB or RGBA colors

});

</script>

app/views/pages/users.html.erb
<div id="users-wrapper">

	<div id="users-box" style="overflow-y:auto;">
		<table class="table table-hover table-light">
			<thead id="table-header">
		    <tr>
		      <th scope="col">Profile</th>
		      <th scope="col">First Name</th>
		      <th scope="col">Last Name</th>
		      <th scope="col">Study</th>
		      <th scope="col">Year</th>
		    </tr>
		  </thead>
			<% @users.each do |user| %>
		  <tbody>
		    <tr>
		    <% if user.profile_picture_file_name.blank? %>	
		    	<td><%= image_tag 'empty-profile', id: "profile", width: "60" %></td>
	      	<% else %>
		      	<td><%= image_tag (user.profile_picture.url(:thumb)), id: "profile", width: "60" %></td>
	      	<% end %>
		      <td><%= user.first_name %></td>
		      <td><%= user.last_name %></td>
		      <td><%= user.course %></td>
		      <td><%= user.degree_level %></td>
		      
		    </tr>
		  </tbody>
		  <% end %>
		</table>
	</div>

</div>