config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get  'pages/index'
  get  'pages/users'
  get  'chatrooms/index'


   


  # get 'chatrooms/index', :to => "chatrooms/index", :as => chatroom_index


  # changes login to /login
	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end	

	

	devise_scope :user do
		get 'sign_up', to: 'devise/registrations#new'
	end	


	resources :chatrooms do
		resource :chatroom_users
	    resources :messages
	end


	resources :posts do 
		member do
			put 'like' => 'posts#vote'
		end
		resources :comments
	end 

	resources :tags

	



	

	# namespace :admin do
 #  		resources :chatromms, :pages
	# end

  resources :direct_messages

  root to: "pages#index"
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { large: "800x800>", medium: "300x300>", thumb: "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	acts_as_taggable





	# post can't get submitted without the user_id
	validates :user_id, presence: true
	belongs_to :user
	has_many :comments, dependent: :destroy


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :vote]
	respond_to :js, :json, :html

	def index
		if params[:tag]
			@posts = Post.all.tagged_with(params[:tag]).order("created_at DESC")
		else 
			@posts =  Post.all.order("created_at DESC")
		end
		@countTags = Post.all.tag_counts_on(:tags).size
		@comments = Comment.all
		@users = User.all
	end 



	# @post = Post.find(params[:id])
	# 	@user = User.find(params[:id])

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id # assign the post to the user who craeted it
		
			if (@post.save)
				redirect_to @post
				flash[:notice] = "Post was successfuly created"
			else
			 	render 'new' 
			 	flash[:alert] = "Post was unsuccessfull, please try again."
			end
	end

	def vote

    	if !current_user.liked? @post
     		@post.liked_by current_user
    	elsif current_user.liked? @post 
      		@post.unliked_by current_user
  		end

    end
 

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end 

	


	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end 

	def edit
		@post = Post.find(params[:id])
	end 

	private 

	def post_params
		params.require(:post).permit(:user_id, :title, :content, :image, :tag_list)
	end

	def set_post 
		@post = Post.find(params[:id])
	end 

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@user, @post], html: { multipart: true  } do |f|  %>

	
	<div class="form-group">
		<%= f.label "Title" %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<!-- <input type="file" class="custom-file-input" id="customFile"> -->
		<%= f.label "image"   %>
		<%= f.file_field :image, class: 'form-control'%>
	</div>
	
	<div class="form-group">
		<%= f.label "Content" %>
		<%= f.cktext_area :content, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label '#Tags' %>
		<%= f.text_field :tag_list, class: 'form-control' %>
	</div>

	<%= f.button :Create, class: 'btn btn-primary' %>
	
	<%= link_to 'Back', posts_path, class: 'btn btn-danger' %>
<% end %>

app/views/posts/_post.html.erb
<div id="boxes">
	<% @posts.each do |post| %>
		<div class="card">
			<%= image_tag post.image.url(:large), class: "img-fluid", style: 'height: 350px' %>
			<div class="card-content">
				<h3 class="post-heading"><%= link_to post.title, post%></h3>
				<hr class="card-hr">

				<p class="post-text"><%= post.content.truncate(140).html_safe %></p>

				<p class="post-creator">Created by <%= User.find(post.user_id).username %></p>
				<p class="post-creator" style="font-size: 0.7rem;"><%= local_time(post.created_at) %></p>

				<% unless post.tag_list.empty? %>
					<p><%= raw post.tags.map  { |t| link_to t.name, posts_path(tag: t.name), class: 'tags' }.join(' ')  %></p>
				<% end %>
				
				<button class="btn btn-primary">
				 	<i id="like-color" class="fas fa-heart"></i>
				 	<span class="likes-count"><%= post.get_upvotes.size  %></span>
				</button>
				<br>
				<hr>
				
				
				
				
				<!-- <button><%= link_to 'Read More', post, class: 'btn btn-primary read-post-btn'%></button> -->

				<%= link_to 'Read More', post, class: 'btn btn-primary read-post-btn'%>


			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="post-form-wrapper">
	<div class="post-form">
		<h3 class="new-event" ">Edit <%= @post.title  %></h3>
		<%= render 'form' %>
	</div>
</div>

app/views/posts/index.html.erb
<div id="fakeLoader"></div>
<div id="posts-home-wrapper">
	
	<div id="header">
		<p id="main-heading">Post things for your friends to see</p>
		<p>Create events, meetings, day trips and more!</p>
		 <hr class="hr-custom">
	</div>

	<div id="new-post-btn">
		<%= link_to 'Add post', new_post_path, class: 'btn btn-danger', id: "add-post-button"  %>
	</div>

	
	<div id="dashboard-btn">
		<%= link_to 'Back', root_path, class: 'btn btn-danger', id: "back-to-dash"  %>
	</div>

	
	<div id="post-count-section">
		<p id="count-post"><i class="fas fa-calendar-alt"></i> Posts: <%= @posts.count %></p>

		<p id="count-user"><i class="fas fa-users"></i> Users: <%= @users.count %></p>
		
		<p id="count-comment"><i class="fas fa-comments"></i> Comments: <%= @comments.count %></p>

		<p id="count-tags"><i class="fas fa-hashtag"></i> Tags:  <%= @countTags %></p>
	</div>
	
	
		
  	

	<div id="posts-section">
		<%= render 'post' %>
	</div>


</div>
<script type="text/javascript">

$("#fakeLoader").fakeLoader({
timeToHide:1200, //Time in milliseconds for fakeLoader disappear

zIndex:"999",//Default zIndex

spinner:"spinner1",//Options: 'spinner1', 'spinner2', 'spinner3', 'spinner4', 'spinner5', 'spinner6', 'spinner7'

bgColor:"#216c98", //Hex, RGB or RGBA colors

// imagePath:"yourPath/customizedImage.gif" //If you want can you insert your custom image
});

</script>

app/views/posts/new.html.erb
<div class="post-form-wrapper">
	<div class="post-form">
		<h3 class="new-event" ">Create a new event</h3>
		<%= render 'form'  %>
	</div>
</div>

app/views/posts/show.html.erb
<div id="buttons-wrapper">
	<div id="show-update-button-section">
			<%= link_to 'Back', posts_path, class: 'btn btn-primary', id: 'show-back-button' %>
			 <% if current_user == @post.user %>
				<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning', id: 'show-edit-button' %>
				<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', id: 'show-delete-button' %>
			<% end %>
	</div>
</div>


<div id="post-show-wrapper">

	<div id="show-header-section">
		<h1 class="header"><%= @post.title  %></h1>
		<p class="post-creator"><i class="far fa-calendar-alt"></i> Created by <%= User.find(@post.user_id).username %> on <%= local_time(@post.created_at) %></p>
		<hr class="hr">
	</div>

	<div id="show-post-images-section">
		<%= image_tag @post.image.url, class: 'img-fluid main-image' %>
		<hr>
	</div>

	<div id="show-content-section">
		<div id="title-like">
			<h1><%= @post.title  %></h1>
				<%= link_to like_post_path(@post), class: 'like-btn', method: :put, remote: :true do %>
					<button class="btn btn-success">
					 	<i id="like-color" class="fas fa-heart"></i>
					 	<span class="likes-count"><%= @post.get_upvotes.size  %></span>
					</button>
				<% end %>
				
				<% unless @post.tag_list.empty? %>
				
					<%= render partial: "tags/tag", collection: @post.tags, class: 'tags'  %>
			
				<% end %>
				
			
			
		
		</div>
		<br>
		<p><%= @post.content.html_safe  %></p>
	</div>


	<div id="show-comments-section">


		<% if @post.comments.count > 1 %>
			<h4 style="color: black;"><%= @post.comments.count %> Comments</h4>
		<% else %>
			<h4 style="color: black;"><%= @post.comments.count %> Comment</h4>
		<% end %>
		

		<%= render @post.comments   %>
		<div class="comments-form">
			<hr>
			<h3>Leave a reply</h3>
			<%= render 'comments/form'  %>
		</div>
	</div>
	

	

</div>

app/views/posts/vote.js.erb
<% if current_user.liked? @post %>
	$('.like-btn').addClass('liked');
	$('#like-color').css('color', 'red')
<% else %>	
	$('.like-btn').removeClass('like-btn');
	$('#like-color').css('color', '#30353a')
<% end %>	

$('.likes-count').html('<%= @post.get_upvotes.size %>');